### ISSUE TITLE
Import Error while importing tweetscrape

### ISSUE THREAD

**Issue by rvssatyaditya** [5hirish/tweet_scrapper#5]
I'm getting this while importing the library.

from tweetscrape.profile_tweets import TweetScrapperProfile
tweet_scrapper = TweetScrapperProfile("@5hirish", 1)
tweets = tweet_scrapper.get_profile_tweets()
for tweet in tweets:
    print(str(tweet))
ModuleNotFoundError: No module named 'tweetscrape'

**Comment by 5hirish** [comment]
@rvssatyaditya Fixed the issue, `pip install tweetscrape --upgrade`
